-- MySQL Script generated by MySQL Workbench
-- Sun May 24 15:27:15 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cyer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cyer` ;

-- -----------------------------------------------------
-- Schema cyer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cyer` DEFAULT CHARACTER SET utf8mb4 ;
USE `cyer` ;

-- -----------------------------------------------------
-- Table `members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `members` ;

CREATE TABLE IF NOT EXISTS `members` (
  `m_id` INT(11) NOT NULL AUTO_INCREMENT,
  `m_email` VARCHAR(100) NOT NULL,
  `m_pwd` VARCHAR(50) NOT NULL,
  `m_name` VARCHAR(50) NOT NULL,
  `m_phone` VARCHAR(20) NOT NULL,
  `m_address` VARCHAR(250) NULL DEFAULT NULL,
  `m_role` INT(11) NOT NULL,
  PRIMARY KEY (`m_id`),
  UNIQUE INDEX `m_email_UNIQUE` (`m_email` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders` ;

CREATE TABLE IF NOT EXISTS `orders` (
  `o_id` INT(11) NOT NULL AUTO_INCREMENT,
  `m_id` INT(11) NOT NULL,
  `o_date` DATETIME NOT NULL,
  `o_total_price` INT(11) NOT NULL,
  `o_shupping` VARCHAR(50) NOT NULL,
  `o_address` VARCHAR(250) NOT NULL,
  `o_payment` VARCHAR(50) NOT NULL,
  `o_status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`o_id`),
  INDEX `fk1_m_id_idx` (`m_id` ASC) ,
  CONSTRAINT `fk1_m_id`
    FOREIGN KEY (`m_id`)
    REFERENCES `members` (`m_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products` ;

CREATE TABLE IF NOT EXISTS `products` (
  `p_id` INT(11) NOT NULL AUTO_INCREMENT,
  `p_name` VARCHAR(50) NOT NULL,
  `p_price` INT(11) NOT NULL,
  `p_stock` INT(11) NOT NULL,
  `p_desc` TEXT NOT NULL,
  `p_category` VARCHAR(50) NOT NULL,
  `p_image` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`p_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `orders_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orders_items` ;

CREATE TABLE IF NOT EXISTS `orders_items` (
  `item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `o_id` INT(11) NOT NULL,
  `p_id` INT(11) NOT NULL,
  `item_quantity` INT(11) NOT NULL,
  `item_unit_price` INT(11) NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk1_o_id_idx` (`o_id` ASC) ,
  INDEX `fk1_p_id_idx` (`p_id` ASC) ,
  CONSTRAINT `fk1_o_id`
    FOREIGN KEY (`o_id`)
    REFERENCES `orders` (`o_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk1_p_id`
    FOREIGN KEY (`p_id`)
    REFERENCES `products` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reviews` ;

CREATE TABLE IF NOT EXISTS `reviews` (
  `r_id` INT(11) NOT NULL AUTO_INCREMENT,
  `p_id` INT(11) NOT NULL,
  `m_id` INT(11) NOT NULL,
  `r_stars` INT(11) NOT NULL,
  `r_content` TEXT NULL DEFAULT NULL,
  `r_date` DATETIME NOT NULL,
  PRIMARY KEY (`r_id`),
  INDEX `fk2_p_id_idx` (`p_id` ASC) ,
  INDEX `fk2_m_id_idx` (`m_id` ASC) ,
  CONSTRAINT `fk2_m_id`
    FOREIGN KEY (`m_id`)
    REFERENCES `members` (`m_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2_p_id`
    FOREIGN KEY (`p_id`)
    REFERENCES `products` (`p_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `site_counter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `site_counter` ;

CREATE TABLE IF NOT EXISTS `site_counter` (
  `count_id` INT(11) NOT NULL,
  `total_views` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`count_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
